[package]
name = "rspacman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
kira = "0.7.3"
rand = "0.8.5"
random = "0.13.2"
time = "0.3.20"
